version: "3.7"
services:
  web:
    links:
      - db
    depends_on:
      - db
      - redis
    build: ./flask
    ports:
      - "8000:8000"
    volumes:
      - ./flask:/code
    command: flask run --host 0.0.0.0 --port 8000
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py

  redis:
    image: "redis:6.2.5-alpine"
  
  db:
    image: "mysql:8.0.26"
    ports:
     - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro
  
  rest:
    links:
      - db
    build: ./fastapi
    ports:
      - "5000:5000"
    volumes:
      - ./fastapi:/code
