version: "3.7"
services:
  web:
    links:
      - db
    build: ./flask
    ports:
      - "127.0.0.1:8000:8000"
    command: gunicorn -b 0.0.0.0:8000 app:app

  redis:
    image: "redis:6.2.5-alpine"
  
  db:
    image: "mysql:8.0.26"
    ports:
     - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro
  
  rest:
    links:
      - db
    build: ./fastapi
    ports:
      - "5000:5000"
